### ISSUE TITLE
link failure

### ISSUE THREAD

**Issue by sajis997** [rust-pcap/pcap#327] opened 2024-02-15 11:50 UTC
I am trying to add the crate (pcap = "1.2.0") to my project in windows 11 platform with rust 1.76.0 installed. While building I am getting the following link error:

 LINK : fatal error LNK1181: cannot open input file 'wpcap.lib'

**Comment by Wojtek242** [comment] 2024-02-15 11:54
Do you have Npcap installed as per the instructions here: https://github.com/rust-pcap/pcap#windows?

**Comment by sajis997** [comment] 2024-02-15 14:33
Npcap is installed, sdk extracted and path to the extraction is also added to the user's path environment variable. I could echo the path on the  command line. But while compiling and linking with the crate , the link error remains.

**Comment by sajis997** [comment] 2024-02-15 14:47
![image](https://github.com/rust-pcap/pcap/assets/2903107/925f7fba-b6ae-4b1b-8cb6-334f328b25e7)

Only one option is checked as above, do we need to check more ? which one ?

**Comment by m-vz** [comment] 2024-02-17 18:05
@sajis997 The guide says to add the path to the `LIB` variable, not to `PATH`...

However, I see the same linker error when trying to build my project on Windows. My `LIB` variable is set up as follows:

![Capture](https://github.com/rust-pcap/pcap/assets/4547497/4d26dfd2-f95c-4056-88a2-b9c8ea73b57c)

**Comment by Stargateur** [comment] 2024-02-17 20:10
if you use windows variable environment you need to restart your shell window. if you start going crazy, you can try copy all lib file directly in your project root maybe it will work.

**Comment by m-vz** [comment] 2024-02-18 17:13
I found out how to set the ENV variables in a build script, seems simpler... I'm still unsure though about what the difference between the `LIB` and the `LIBPCAP_LIBDIR` variables is. They're both mentioned in the readme. Do they both point to the same location?

**Comment by Wojtek242** [comment] 2024-02-23 14:01
`LIB` is a Windows environment variable. `LIBPCAP_LIBDIR` is an environment variable specific to this crate. If you have `LIB` set correctly, you should not need `LIBPCAP_LIBDIR`.

As this is not a bug in the crate, but a build issue that appears resolved, I am closing the issue.

If this is still an issue for you, please re-open, but be aware that I do not own a Windows machine so I cannot help you.

**Closed by Wojtek242** 2024-02-23 14:01 UTC
